### PR TITLE
resolve inaugural issue

### LINKED ISSUE #1: primitive_subtract is not working correctly.
it is just adding the args.

### PR DESCRIPTION
**Pull request by penryu**
fixes #1

### CODE REVIEW

File: prim.c [hunk 1]
```diff
@@ -111,25 +111,35 @@ obj_t *primitive_add(env, args)
...
-  obj_t *node, *node_val;
 
-  for (node = args; node != nil; node = CDR(node)) {
+  node = args;
+  if (nil == node)
+    return alloc_int(0);
+
+  node_val = eval(CAR(node), env);
+  if (TINT == node_val->type)
+    sum += node_val->value.i;
```
Comment (jgouly) [inline prim.c:124]: s/+=/=/ ?

Comment (AaronJackson) [reply prim.c:124]: hmm

Comment (penryu) [reply prim.c:124]: It evaluates to
```
0 + x
```
*shrug*

If it's too many wasted cycles, I'm happy to see it changed.
